### PR TITLE
Bump core20 to core24

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by abitrolly** [comment]
@jnsgruk done.

Why releases are not promoted to `stable`? https://forum.snapcraft.io/t/why-releases-are-not-promoted-to-stable/43307

Is it possible to give it read/write access to `/tmp`?

**Comment by jnsgruk** [comment]
Thanks for the iteration.

Once this has been merged, I'll be able to promote it to `stable`.

Why does the app need access to `/tmp`? It already has access to the user's home directory, and to removable media.

**Comment by jnsgruk** [comment]
@abitrolly if you're interested, you could look at porting the GitHub Workflows from one of our other snaps (discord, signal-desktop) which would add better release automation 😄

**Comment by abitrolly** [comment]
> Why does the app need access to /tmp? It already has access to the user's home directory, and to removable media.

Because the primary use case for `wormhole` is to send discardable files that need to be processed and sent further on another PC. Like errors from this snap that I paste to `wormhole` tracker. Home dirs are usually persistent and their synchronization is better handled by `syncthing` and the likes.

**Comment by abitrolly** [comment]
> @abitrolly if you're interested, you could look at porting the GitHub Workflows from one of our other snaps (discord, signal-desktop) which would add better release automation 😄

@jnsgruk I know all that automation (unfortunately), and the process of copy-pasting this block https://github.com/snapcore/action-publish?tab=readme-ov-file#snapcraft-publish-action into https://github.com/snapcrafters/magic-wormhole/blob/master/.github/workflows/test-snap-can-build.yml should be done by admins who have to configure credentials.

**Comment by brlin-tw** [comment]
@abitrolly 

> Because the primary use case for `wormhole` is to send discardable files that need to be processed and sent further on another PC.

I failed to see how it could not be done in a regular directory accessible by snaps, as I don't rely on the /tmp directory's volatile characteristics to store such files.

Regardlessly, it's an architectural (and security) limitation that snap apps don't have access to the /tmp directory so the use case won't be supported.

> the process of copy-pasting this block [https://github.com/snapcore/action-publish?tab=readme-ov-file#snapcraft-publish-action](https://github.com/snapcore/action-publish?tab=readme-ov-file#snapcraft-publish-action) into [https://github.com/snapcrafters/magic-wormhole/blob/master/.github/workflows/test-snap-can-build.yml](https://github.com/snapcrafters/magic-wormhole/blob/master/.github/workflows/test-snap-can-build.yml) should be done by admins who have to configure credentials.

Anyone can make the code change, it's just that the credentials need to be set by others.

**Comment by jnsgruk** [comment]
> Anyone can make the code change, it's just that the credentials need to be set by others.

Indeed, if you make the code changes, I'll review and make sure the credentials are in place 🙂

**Comment by abitrolly** [comment]
> Regardlessly, it's an architectural (and security) limitation that snap apps don't have access to the /tmp directory so the use case won't be supported.

If you change the behavior of original project, the good practice is to add a patch that explains users how to fix the problem, because instead they are left with hardly readable `wormhole` innards on the screen.

The whole experience with snaps is frustrating.

**Comment by brlin-tw** [comment]
@abitrolly

> If you change the behavior of the original project, the good practice is to add a patch that explains to users how to fix the problem

You have a good point, I've filed #19 for the possibility to improve in that regard.

**Pull request merged**
